### ISSUE TITLE
adb-info fails with non-informative error when image not running 

### ISSUE THREAD

**Issue by maxandersen** [bexelbie/vagrant-adbinfo#52]
Running `eval "$(vagrant adbinfo)"` this morning not knowing if vagrant was properly up and running I got the following error:

```
eval "$(vagrant adbinfo)"                                                                                                                      ✚
/Users/max/.vagrant.d/gems/gems/vagrant-adbinfo-0.0.9/lib/command.rb:37:in `block in execute': undefined method `[]' for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from /Users/max/.vagrant.d/gems/gems/vagrant-adbinfo-0.0.9/lib/command.rb:33:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

Seems like it is failing because the CDK was not yet running.

This should be handled better. ie. print to standard error that it could not find whatever thing it is looking for.

**Comment by navidshaikh** [comment]
similar to https://github.com/projectatomic/vagrant-adbinfo/issues/30 , closing.
