### ISSUE TITLE
OS is not a module (TypeError) - Windows

### ISSUE THREAD

**Issue by inlandsee** [bexelbie/vagrant-adbinfo#67]
```
DEBUG host: Trying: windows
 INFO host: Detected: windows!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 5 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x4bd4bc8>
e:/vagrant/gems/gems/vagrant-adbinfo-0.0.9/lib/command.rb:1:in `<top (required)>': OS is not a module (TypeError)
        from e:/vagrant/gems/gems/vagrant-adbinfo-0.0.9/lib/vagrant-adbinfo.rb:7:in `require_relative'
        from e:/vagrant/gems/gems/vagrant-adbinfo-0.0.9/lib/vagrant-adbinfo.rb:7:in `block in <class:Plugin>'
        from e:/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:36:in `call'
        from e:/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:36:in `execute'
        from e:/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
        from e:/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

**Comment by inlandsee** [comment]
I don't code enough Ruby to know the 'right' way to address this issue but if I split the OS module out into its own 'os.rb' file which I relative_require from command.rb then everything works as expected.

```
require_relative 'os'
module VagrantPlugins
  module DockerInfo
    ...
   end
end
```

$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]

**Comment by brgnepal** [comment]
@inlandsee , that would be an ideal solution to extract OS inspection methods into separate module in `os.rb` which forces to follow <a href="https://en.wikipedia.org/wiki/Single_responsibility_principle" target="_blank">OOPs Single responsibility principle</a>.
